export const bookyTokens = {
  fontFamily: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
  },
  fontSize: {
    display3xl: 'var(--font-size-display-3xl)',
    display2xl: 'var(--font-size-display-2xl)',
    displayXl: 'var(--font-size-display-xl)',
    displayLg: 'var(--font-size-display-lg)',
    displayMd: 'var(--font-size-display-md)',
    displaySm: 'var(--font-size-display-sm)',
    displayXs: 'var(--font-size-display-xs)',
    textXl: 'var(--font-size-text-xl)',
    textLg: 'var(--font-size-text-lg)',
    textMd: 'var(--font-size-text-md)',
    textSm: 'var(--font-size-text-sm)',
    textXs: 'var(--font-size-text-xs)',
  },
  lineHeight: {
    display3xl: 'var(--line-height-display-3xl)',
    display2xl: 'var(--line-height-display-2xl)',
    displayXl: 'var(--line-height-display-xl)',
    displayLg: 'var(--line-height-display-lg)',
    displayMd: 'var(--line-height-display-md)',
    displaySm: 'var(--line-height-display-sm)',
    displayXs: 'var(--line-height-display-xs)',
    textXl: 'var(--line-height-text-xl)',
    textLg: 'var(--line-height-text-lg)',
    textMd: 'var(--line-height-text-md)',
    textSm: 'var(--line-height-text-sm)',
    textXs: 'var(--line-height-text-xs)',
  },
  colors: {
    base: {
      white: 'var(--base-white)',
      black: 'var(--base-black)',
    },
    neutral: {
      25: 'var(--neutral-25)',
      50: 'var(--neutral-50)',
      100: 'var(--neutral-100)',
      200: 'var(--neutral-200)',
      300: 'var(--neutral-300)',
      400: 'var(--neutral-400)',
      500: 'var(--neutral-500)',
      600: 'var(--neutral-600)',
      700: 'var(--neutral-700)',
      800: 'var(--neutral-800)',
      900: 'var(--neutral-900)',
      950: 'var(--neutral-950)',
    },
    primary: {
      100: 'var(--primary-100)',
      200: 'var(--primary-200)',
      300: 'var(--primary-300)',
    },
    accent: {
      red: 'var(--accent-red)',
      screenError: 'var(--screen-error)',
      green: 'var(--accent-green)',
      statusGreen: 'var(--status-green)',
      yellow: 'var(--accent-yellow)',
    },
  },
  radius: {
    none: 'var(--radius-none)',
    xxs: 'var(--radius-xxs)',
    xs: 'var(--radius-xs)',
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    '3xl': 'var(--radius-3xl)',
    '4xl': 'var(--radius-4xl)',
    full: 'var(--radius-full)',
  },
  spacing: {
    none: 'var(--space-none)',
    xxs: 'var(--space-xxs)',
    xs: 'var(--space-xs)',
    '1_5': 'var(--space-1_5)',
    md: 'var(--space-md)',
    lg: 'var(--space-lg)',
    xl: 'var(--space-xl)',
    '2xl': 'var(--space-2xl)',
    '3xl': 'var(--space-3xl)',
    '4xl': 'var(--space-4xl)',
    '5xl': 'var(--space-5xl)',
    '6xl': 'var(--space-6xl)',
    '7xl': 'var(--space-7xl)',
    '8xl': 'var(--space-8xl)',
    '9xl': 'var(--space-9xl)',
    '10xl': 'var(--space-10xl)',
    '11xl': 'var(--space-11xl)',
  },
  shadow: {
    card: 'var(--shadow-card)',
    lg: 'var(--shadow-lg)',
  },
  layout: {
    desktopCanvas: 'var(--layout-desktop-canvas)',
    desktopHeader: 'var(--layout-desktop-header)',
    desktopGutter: 'var(--layout-desktop-gutter)',
    mobileCanvas: 'var(--layout-mobile-canvas)',
    mobileHeader: 'var(--layout-mobile-header)',
    mobileGutter: 'var(--layout-mobile-gutter)',
    mobileContent: 'var(--layout-mobile-content)',
  },
} as const;

export const bookySemanticTokens = {
  background: 'var(--color-surface)',
  foreground: 'var(--color-text)',
  muted: 'var(--color-muted)',
  border: 'var(--color-border)',
  brand: 'var(--color-brand)',
  brandSubtle: 'var(--color-brand-subtle)',
  danger: 'var(--color-danger)',
  success: 'var(--color-success)',
  warning: 'var(--color-warning)',
} as const;
